### ISSUE TITLE
Error Installing through Pip on Python3.7 on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by erb13020** [gfairchild/pyxDamerauLevenshtein#27]
I'm unable to install this on my local Linux Ubuntu 18.04 running Python3.7.

My current install process / what I have tried:

Try installing some possible missing dependencies.

Create a fresh new virtual environment for Python3.7

`sudo apt-get install -yqq --noinstall-recommends apt-utils gcc build-essential`

Try upgrading these packages
`python3.7 -m pip install --upgrade pip setuptools wheel`

Try installing the package
`python3.7 -m pip install --no-cache-dir pyxDamerauLevenshtein`

Note: These commands worked on a Docker image using Python3.7:slim-buster as the base image. I have also tried this
on a few other machines running 18.04

Current Output:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting pyxDamerauLevenshtein
  Downloading pyxDamerauLevenshtein-1.6.1.tar.gz (55 kB)
     |████████████████████████████████| 55 kB 2.9 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.7 /home/erb13020/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_901baqu
       cwd: /tmp/pip-install-wnfgf6t1/pyxdameraulevenshtein_c6df6562c7e04fd6a22642aacd88bc26
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/erb13020/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/erb13020/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/erb13020/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 108, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/erb13020/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 99, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 /home/erb13020/.local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_901baqu Check the logs for full command output.
```

Any hints?

**Comment by gfairchild** [comment]
Have you tried installing to a local virtual environment rather than the system root environment? That is, something like this:

```
sudo apt install python3-venv
python3 -m venv /path/to/env
source /path/to/env
pip install --upgrade pip setuptools wheel
pip install numpy
pip install pyxDamerauLevenshtein
```

What does that get you?

**Comment by gfairchild** [comment]
Are you still experiencing this issue? I've released a few new versions in the meantime, and you might try that as well.

**Comment by gfairchild** [comment]
I'm going to go ahead and close this issue since I'm not receiving any feedback.
